# Generated by Django 3.1.1 on 2024-03-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0002_auto_20240326_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approval', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.doctorprofile')),
                ('hospitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=255)),
                ('Bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('HealthPath', models.CharField(max_length=1000)),
                ('availability', models.BooleanField(default=True)),
                ('Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.hospitalprofile')),
                ('doner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.BooleanField(default=True)),
                ('Organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.organdonation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.doctorprofile')),
                ('hospitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField()),
                ('admint_date', models.DateField()),
                ('surgery_status', models.BooleanField(default=False)),
                ('comments_doctor', models.CharField(max_length=1000, null=True)),
                ('consultaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.consutation')),
                ('organrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation.organrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
