# Generated by Django 3.1.1 on 2024-03-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240326_1634'),
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonation',
            name='doner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile'),
        ),
    ]
