# Generated by Django 3.1.1 on 2024-04-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0003_auto_20240408_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='consultaion',
        ),
    ]
