# Generated by Django 3.1.1 on 2024-04-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0004_remove_surgery_consultaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='organrequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donation.organrequest'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_status',
            field=models.BooleanField(default=True),
        ),
    ]
