# Generated by Django 3.1.1 on 2024-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0006_auto_20240408_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='HealthRecord',
            field=models.FileField(blank=True, null=True, upload_to='HealthFile'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='is_healthrecord_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='organ',
            field=models.CharField(choices=[('Kidneys', 'Kidneys'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Heart', 'Heart'), ('Pancreas', 'Pancreas'), ('Intestines', 'Intestines'), ('Hands', 'Hands'), ('Eye', 'Eye')], max_length=255),
        ),
    ]
