# Generated by Django 5.0.6 on 2025-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0010_remove_organrequest_organ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
