# Generated by Django 5.0.6 on 2025-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0012_organrequest_donar_organrequest_donar_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
