# Generated by Django 5.0.6 on 2025-03-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0013_organrequest_date'),
        ('Home', '0008_receiverprofile_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrequest',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_for_request', to='Home.doctorprofile'),
        ),
    ]
