# Generated by Django 3.1.1 on 2024-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
