# Generated by Django 5.0.6 on 2025-03-19 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_1')),
                ('MedicineBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Block_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_2')),
                ('MedicineBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Block_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_3')),
                ('MedicineBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(upload_to='profilepic')),
                ('medical_doc', models.FileField(upload_to='documents')),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
