# Generated by Django 5.0.6 on 2025-03-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_block_1_block_2_block_3_block_4_receiverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='receiverprofile',
            name='medical_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
