# Generated by Django 5.0.6 on 2025-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonation',
            old_name='requested_group',
            new_name='donated_group',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodreceptrequests',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
